### ISSUE TITLE
Open-source the database json with some sample data?

### ISSUE THREAD

**Issue by davidvavra** [novoda/bonfire-firebase-sample#1]
Hi, great app and article! I'm also developing an app with Firebase Database and it's tricky to structure the data correctly. Could you also open-source your database structure with few sample data? It would help to understand your code.

**Comment by Dorvaryn** [comment]
@davidvavra Great Idea I'll try and create a sample that showcases the structure.

**Comment by Dorvaryn** [comment]
There is now a sample JSON in the server folder => https://github.com/novoda/bonfire-firebase-sample/blob/master/server/database.sample.json

**Comment by davidvavra** [comment]
Awesome, thanks!
