### ISSUE TITLE
Presenter with Fragments

### ISSUE THREAD

**Issue by linxydmhg** [novoda/bonfire-firebase-sample#13]
Hello, this is not a issue but a question:

This sample shows how to use a presenter with a activity and a custom view inflating a layout. How would this be implemented in the case where fragments are needed e.g. a navigation drawer?

Would you implement the MasterActivity as normal and have it create Fragments, and then have the fragments create a presenter and inflate a CustomView? Or would you not use fragments at all and just use the custom views and let them create the presenter/be the displayer?

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
