### ISSUE TITLE
Moving message timestamp to DB ?

### ISSUE THREAD

**Issue by clackbib** [novoda/bonfire-firebase-sample#2]
Hi!

Not really an issue per se, but it's something that would be nice to be resolved -
I've looked at http://stackoverflow.com/questions/25744398/retrieve-servervalue-timestamp-from-firebase-in-android-app-when-data-is-sent but haven't tried myself, perhaps show us?

Thanks again for this, the core / app separation makes it really neat!

**Comment by Dorvaryn** [comment]
Hi, yes moving the timestamp server side was on our list of features, unfortunately we didn't have the time to do everything we wanted to do. 
We will most likely spend some more time on this project a bit later so we can add that at that time. In  the meantime if anyone wants to play with the code and PR for this we always welcome PRs 😄

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
